# Generated by Django 4.2.4 on 2023-10-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basegamemodel',
            name='autor',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basegamemodel',
            name='description',
            field=models.TextField(default=1, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basegamemodel',
            name='translate',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basegamemodel',
            name='word',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
