# Generated by Django 4.2.4 on 2023-10-05 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base_game', '0003_basegamemodel_level_alter_basegamemodel_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basegamemodel',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
