# Generated by Django 4.2.4 on 2023-10-30 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_pages_description_alter_playlist_description'),
        ('tips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.pages')),
            ],
        ),
    ]
