# Generated by Django 4.2.4 on 2023-11-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0002_pagelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagelink',
            name='icons',
            field=models.ImageField(blank=True, null=True, upload_to='user_icons/'),
        ),
    ]
