# Generated by Django 4.2.4 on 2023-10-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_pages_description_pages_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='description',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
