# Generated by Django 4.2.4 on 2023-10-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0004_sentence_translate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='translate',
            field=models.TextField(default='Нема'),
        ),
    ]
