# Generated by Django 4.2.4 on 2023-11-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuessWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guess_word', models.CharField(default='Нема', max_length=200)),
                ('help_words', models.CharField(default='Нема', max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='guess_word_image/')),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default='A1', max_length=2)),
                ('language', models.CharField(choices=[('en', 'English'), ('de', 'German')], max_length=2)),
            ],
        ),
    ]
